### ISSUE TITLE
2.4GHz band

### ISSUE THREAD

**Issue by array81** [ehambuch/ForceWifi5#2]
The application is called "Force Wifi 5 GHz" but in the settings there is the possibility to choose whether to prefer the 2.4GHz or 5GHz network so I guess the app can force the 2.4GHz  network too. However I noticed that my MI 10T Pro continues to connect to network 5GHz even though I prefer network 2.4GHz. Am I doing something wrong?

**Comment by ehambuch** [comment]
Dear Martin,

Probably not, but with higher Android versions the Wifi cannot be "forced"
but only be "suggested" to another frequency.

The FAQ gives some hints, you probably gave to switch off and on again
manually: https://sites.google.com/site/erichambuch/forcewifi5

The graphical overview of the app provides the information what is going on.

Regards
Eric

Martin ***@***.***> schrieb am Fr., 29. Sept. 2023, 08:32:
