### ISSUE TITLE
"so 2.4 Ghz as well as 5 or 6 GHz. Obviously this is not the case" -- can be a great feature

### ISSUE THREAD

**Issue by TAbdiukov** [ehambuch/ForceWifi5#3]
Unfortunately, 'obvious' 2.4/5/6GHz support is not so obvious, and there are no Android checker apps (AFAIK) to check 2.4/5/6 GHz support.  Even though it's a simple API call in Android (at least to check 5GHz support). 

I actually use this app to check 5/6 GHz support, so I have a suggestion.

Maybe this "please deinstall the app" message can be made into a small feature, where the user can see what bands are supported, and the user can decide if he/she wants to use this app?

Thanks

**Comment by ehambuch** [comment]
Hi,

Many thanks for your request. I had a look into the issue and you can see
the supported WiFi bands in the settings when checking the "Preferred Wifi"
bands. There are also a lot if "system information" apps in Google Play
that displays the wifi capabilities.

If a device has Wifi, then it supports at least 2.4 Ghz. Depending on the
chipset 5 Ghz, 6 or 60 is supported additionally, but I am not aware of any
device only supporting 5 or 6 Ghz.

Regards

Eric

TAbdiukov ***@***.***> schrieb am So., 16. Juni 2024, 05:46:

**Comment by ehambuch** [comment]
Won't fix.
